name: Build on Windows2

on: push

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Getting Ready. 
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force) && cd D:\a\ && mkdir b && cd b && Invoke-WebRequest -Uri https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile D:/a/b/ngrok-stable-windows-amd64.zip && Expand-Archive D:/a/b/ngrok-stable-windows-amd64.zip D:/a/b/ -Force && D:/a/b/ngrok.exe authtoken 1vlUDOQ4fclJaGPPjZFZCrxue4H_7rHRopB69cNaS9uPhmw6T && D:/a/b/ngrok.exe tcp 3389
